services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: springcommunity
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
