server:
  port: 8080
# DB config
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcommunity?serverTimezone=Asia/Seoul
    username: root
    password: '!@Skdud340'
  # DB update
  jpa:
    hibernate:
      ddl-auto: update
    # sql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  # Redis
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  secret_key: RGVjb2RlIGZyb20gQmFzZTY0IGZvcm1hdFNpbXBseSBlbnRlciB5b3VyIGRhdGEgdGhlbi
  expired_time: 86400000

