name: CI

on:
  push:
    branches: [ main, feature/* ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0 # 사용할 MySQL 버전
        ports:
          - 3306:3306 # 호스트와 컨테이너의 MySQL 포트를 매핑
        env:
          MYSQL_ROOT_PASSWORD: root_password # 루트 비밀번호
          MYSQL_DATABASE: testdb # 기본 데이터베이스 생성
          MYSQL_USER: testuser # 사용자 이름
          MYSQL_PASSWORD: testpassword # 사용자 비밀번호
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: git_clone
        uses: actions/checkout@v3

      - name: java_setting
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-database.yml
        run: |
          cd ./src/main/resources
          touch ./application-database.yml
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/testdb" >> ./application-database.yml
          echo "spring.datasource.username=testuser" >> ./application-database.yml
          echo "spring.datasource.password=testpassword" >> ./application-database.yml
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ./application-database.yml
        shell: bash

      - name: run
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

      - name: docker run
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
