name: CI

on:
  push:
    branches: [ main, feature/* ]

permissions: # Github Actions가 불필요한 내용 수정 방지를 위해 "읽기" 권한 부여
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: git_clone # 이 단계의 이름
        uses: actions/checkout@v3 # 내 소스코드를 github Actions VM에 복사

      - name: java_setting
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 자바 배포판 지정

      - name: make application-database.yml # 배포환경에서는 다른 yml 파일로 설정시키기 위해 새로 만들어줌
        run: |

          cd ./src/main/resources
          
          # application-database.yml 파일 생성
          touch ./application-database.yml
          
          # 현재 나의 경로에 application-database.yml이 없다면, 내가 secret으로 설정한 database의 값을 넣어라
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash # bash shell에서 작동되게 설정


      - name: run
        run: |
          echo "VM Public IP: $(curl ifconfig.me)"
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

      # docker 행동 정의
      - name: docker build and push
        run: |

          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
      - name: docker run
        uses: appleboy/ssh-action@master